---

dist: xenial
sudo: required

language: c

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip

install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo add-apt-repository ppa:vala-team/next -y
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq valac valadoc libvala-0.40-dev
    libvaladoc-0.40-dev unzip python3-pip libglib2.0-dev libsoup2.4-dev
    libmysqlclient-dev sphinxsearch libjson-glib-dev libgee-0.8-dev
  - pip3 install meson
  - sudo unzip ninja-linux.zip -d /usr/local/bin
  - "bash -c 'source ~/.nvm/nvm.sh; nvm install 6'"
  - "bash -c 'source ~/.nvm/nvm.sh; nvm use 6; npm install'"

script:
  - "bash -c 'source ~/.nvm/nvm.sh; nvm use 6; npm test'"
  - make build-docs-mini || (cat LOG; false)
