dist: trusty

language: c

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - wget -O valum-0.3.0.zip https://github.com/valum-framework/valum/archive/v0.3.0.zip

install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq valac valadoc libvaladoc-dev unzip python3-pip libglib2.0-dev libsoup2.4-dev
  - pip3 install meson==0.36.0
  - sudo unzip ninja-linux.zip -d /usr/local/bin
  - unzip valum-0.3.0.zip
  - cd valum-0.3.0 && mkdir build && meson --prefix=/usr --buildtype=release build && ninja -C build && sudo ninja -C build install

script:
  - make
